# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Resources/isol_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setStyleSheet("QWidget {\n"
"    font-family: Times New Roman;\n"
"    font-size: 18pt;\n"
"}\n"
"\n"
"/*TAB WIDGET*/\n"
"QTabWidget::pane {\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    height: 600px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    \n"
"    background-color: rgb(167, 24, 50);\n"
"    color: rgb(215, 215, 215);\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"    width: 100px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: rgb(109, 3, 16);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(109, 3, 16);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 0px;\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.mainTabWidget = QtWidgets.QTabWidget(self.mainWidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.mainTabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.mainTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tabCompute = QtWidgets.QWidget()
        self.tabCompute.setStyleSheet("QWidget {\n"
"    /*background-image: url(:/carbonBackground/C:/Users/Dmitry/Downloads/carbon.jpg);*/\n"
"    background-color: black;\n"
"    color: #a71832;\n"
"    font-family: Times New Roman;\n"
"    font-size: 16pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: #d7d7d7;\n"
"    border: 1px solid #a71832;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: rgb(215, 215, 215);\n"
"    background-color: rgb(167, 24, 50);\n"
"}\n"
"\n"
"QPushButton:!enabled {\n"
"color: rgb(215, 215, 215);\n"
"background-color: rgb(88, 2, 13);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: rgb(215, 215, 215);\n"
"background-color: rgb(109, 3, 16);;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"color: rgb(215, 215, 215);\n"
"background-color: rgb(109, 3, 16);;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    color: rgb(215, 215, 215);\n"
"    background-color: rgb(51, 51, 51);\n"
"    border-style: solid;\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    background-color: rgb(167, 24, 50)\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: rgb(215, 215, 215);\n"
"     border: 1px solid #a71832;\n"
"}\n"
"\n"
"/*HORIZONTAL SLIDER*/\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 10px;\n"
"    background: rgb(215, 215, 215);\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(167, 24, 50);\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"    width: 10px;\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::groove:!enabled:horizontal {\n"
"    background: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QSlider::handle:!enabled:horizontal {\n"
"    background: rgb(109, 3, 16);\n"
"}\n"
"QTextEdit {\n"
"    color: rgb(215, 215, 215);\n"
"    border: 1px solid rgb(167, 24, 50); \n"
"    font-family: Times New Roman;\n"
"    font-size: 10pt;\n"
"}")
        self.tabCompute.setObjectName("tabCompute")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabCompute)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 681, 124))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(100)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.leHowIsolatorsCompute = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leHowIsolatorsCompute.setMaxLength(10)
        self.leHowIsolatorsCompute.setAlignment(QtCore.Qt.AlignCenter)
        self.leHowIsolatorsCompute.setObjectName("leHowIsolatorsCompute")
        self.horizontalLayout_4.addWidget(self.leHowIsolatorsCompute)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblComputeIsolatorsMin = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblComputeIsolatorsMin.setEnabled(True)
        self.lblComputeIsolatorsMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblComputeIsolatorsMin.setObjectName("lblComputeIsolatorsMin")
        self.horizontalLayout.addWidget(self.lblComputeIsolatorsMin)
        self.sliderComputeIsolators = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.sliderComputeIsolators.setOrientation(QtCore.Qt.Horizontal)
        self.sliderComputeIsolators.setObjectName("sliderComputeIsolators")
        self.horizontalLayout.addWidget(self.sliderComputeIsolators)
        self.lblComputeIsolatorsMax = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblComputeIsolatorsMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblComputeIsolatorsMax.setObjectName("lblComputeIsolatorsMax")
        self.horizontalLayout.addWidget(self.lblComputeIsolatorsMax)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tabCompute)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 260, 681, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.btnCompute = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCompute.sizePolicy().hasHeightForWidth())
        self.btnCompute.setSizePolicy(sizePolicy)
        self.btnCompute.setObjectName("btnCompute")
        self.horizontalLayout_6.addWidget(self.btnCompute)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btnStop = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setObjectName("btnStop")
        self.btnStop.setEnabled(False)
        self.horizontalLayout_6.addWidget(self.btnStop)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabCompute)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 681, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblFoundIsolators = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lblFoundIsolators.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFoundIsolators.setObjectName("lblFoundIsolators")
        self.horizontalLayout_3.addWidget(self.lblFoundIsolators)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tabCompute)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 350, 681, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.label_5 = QtWidgets.QLabel(self.tabCompute)
        self.label_5.setGeometry(QtCore.QRect(170, 180, 361, 22))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabCompute)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 210, 681, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lePathToFolder = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lePathToFolder.setObjectName("lePathToFolder")
        self.lePathToFolder.setReadOnly(True)
        self.horizontalLayout_2.addWidget(self.lePathToFolder)
        self.btnChooseFolder = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnChooseFolder.setText("...")
        self.btnChooseFolder.setObjectName("btnChooseFolder")
        self.horizontalLayout_2.addWidget(self.btnChooseFolder)
        self.teLogs = QtWidgets.QTextEdit(self.tabCompute)
        self.teLogs.setReadOnly(True)
        self.teLogs.setGeometry(QtCore.QRect(10, 430, 681, 161))
        self.teLogs.setObjectName("teLogs")
        self.mainTabWidget.addTab(self.tabCompute, "")
        self.tabProperties = QtWidgets.QWidget()
        self.tabProperties.setStyleSheet("QWidget {\n"
"    background-color: black;\n"
"    color: #a71832;\n"
"    font-family: Times New Roman;\n"
"    font-size: 16pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: rgb(215, 215, 215);\n"
"    border: 0px solid #a71832;\n"
"}\n"
"\n"
"/*GROUP BOX*/\n"
"QGroupBox {\n"
"    color: #d7d7d7;\n"
"    border: 1px solid rgb(167, 24, 50);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"/*CHECK BOX*/\n"
"QCheckBox {\n"
"    color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(:/images/checkbox_unchecked_hover.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(:/images/checkbox_unchecked_pressed.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(167, 24, 50);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(:/images/checkbox_checked_hover.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image: url(:/images/checkbox_checked_pressed.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:hover {\n"
"    image: url(:/images/checkbox_indeterminate_hover.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    image: url(:/images/checkbox_indeterminate_pressed.png);\n"
"}\n"
"\n"
"/*RADIO BUTTON*/\n"
"QRadioButton {\n"
"color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    \n"
"    background-color: rgb(215, 215, 215);\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover {\n"
"    image: url(:/images/radiobutton_unchecked_hover.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:pressed {\n"
"    image: url(:/images/radiobutton_unchecked_pressed.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    \n"
"    background-color: rgb(167, 24, 50);\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover {\n"
"    image: url(:/images/radiobutton_checked_hover.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed {\n"
"    image: url(:/images/radiobutton_checked_pressed.png);\n"
"}\n"
"\n"
"/*HORIZONTAL SLIDER*/\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 10px;\n"
"    background: rgb(215, 215, 215);\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(167, 24, 50);\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"    width: 10px;\n"
"    height: 30px;\n"
"    border-radius: 5px;\n"
"}")
        self.tabProperties.setObjectName("tabProperties")
        self.gbWhiteLimit = QtWidgets.QGroupBox(self.tabProperties)
        self.gbWhiteLimit.setGeometry(QtCore.QRect(215, 446, 266, 140))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbWhiteLimit.setFont(font)
        self.gbWhiteLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.gbWhiteLimit.setObjectName("gbWhiteLimit")
        self.widget_3 = QtWidgets.QWidget(self.gbWhiteLimit)
        self.widget_3.setGeometry(QtCore.QRect(5, 30, 256, 101))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblWhiteLimitMin = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblWhiteLimitMin.setFont(font)
        self.lblWhiteLimitMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWhiteLimitMin.setObjectName("lblWhiteLimitMin")
        self.gridLayout_4.addWidget(self.lblWhiteLimitMin, 1, 0, 1, 1)
        self.lblWhiteLimitTextValue = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblWhiteLimitTextValue.setFont(font)
        self.lblWhiteLimitTextValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWhiteLimitTextValue.setObjectName("lblWhiteLimitTextValue")
        self.gridLayout_4.addWidget(self.lblWhiteLimitTextValue, 0, 1, 1, 1)
        self.lblWhiteLimitMax = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblWhiteLimitMax.setFont(font)
        self.lblWhiteLimitMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWhiteLimitMax.setObjectName("lblWhiteLimitMax")
        self.gridLayout_4.addWidget(self.lblWhiteLimitMax, 1, 4, 1, 1)
        self.sliderWhiteLimit = QtWidgets.QSlider(self.widget_3)
        self.sliderWhiteLimit.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWhiteLimit.setObjectName("sliderWhiteLimit")
        self.gridLayout_4.addWidget(self.sliderWhiteLimit, 1, 1, 1, 3)
        self.leWhiteLimitValue = QtWidgets.QLineEdit(self.widget_3)
        self.leWhiteLimitValue.setAlignment(QtCore.Qt.AlignCenter)
        self.leWhiteLimitValue.setObjectName("leWhiteLimitValue")
        self.gridLayout_4.addWidget(self.leWhiteLimitValue, 0, 2, 1, 1)
        self.gbGenerateMethod = QtWidgets.QGroupBox(self.tabProperties)
        self.gbGenerateMethod.setGeometry(QtCore.QRect(5, 150, 201, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbGenerateMethod.setFont(font)
        self.gbGenerateMethod.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGenerateMethod.setObjectName("gbGenerateMethod")
        self.rbCrackAddition = QtWidgets.QRadioButton(self.gbGenerateMethod)
        self.rbCrackAddition.setGeometry(QtCore.QRect(10, 60, 179, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbCrackAddition.setFont(font)
        self.rbCrackAddition.setChecked(True)
        self.rbCrackAddition.setObjectName("rbCrackAddition")
        self.rbCrackGeneration = QtWidgets.QRadioButton(self.gbGenerateMethod)
        self.rbCrackGeneration.setGeometry(QtCore.QRect(10, 130, 179, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbCrackGeneration.setFont(font)
        self.rbCrackGeneration.setObjectName("rbCrackGeneration")
        self.gbGenerateParams = QtWidgets.QGroupBox(self.tabProperties)
        self.gbGenerateParams.setGeometry(QtCore.QRect(215, 150, 476, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbGenerateParams.setFont(font)
        self.gbGenerateParams.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGenerateParams.setObjectName("gbGenerateParams")
        self.gbPaletteSmoothing = QtWidgets.QGroupBox(self.gbGenerateParams)
        self.gbPaletteSmoothing.setGeometry(QtCore.QRect(10, 30, 226, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbPaletteSmoothing.setFont(font)
        self.gbPaletteSmoothing.setAlignment(QtCore.Qt.AlignCenter)
        self.gbPaletteSmoothing.setObjectName("gbPaletteSmoothing")
        self.widget = QtWidgets.QWidget(self.gbPaletteSmoothing)
        self.widget.setGeometry(QtCore.QRect(5, 30, 216, 131))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblPaletteSmoothingMin = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblPaletteSmoothingMin.setFont(font)
        self.lblPaletteSmoothingMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPaletteSmoothingMin.setObjectName("lblPaletteSmoothingMin")
        self.gridLayout_2.addWidget(self.lblPaletteSmoothingMin, 1, 0, 1, 1)
        self.lblPaletteSmoothingTextValue = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblPaletteSmoothingTextValue.setFont(font)
        self.lblPaletteSmoothingTextValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPaletteSmoothingTextValue.setObjectName("lblPaletteSmoothingTextValue")
        self.gridLayout_2.addWidget(self.lblPaletteSmoothingTextValue, 0, 1, 1, 1)
        self.lblPaletteSmoothingMax = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblPaletteSmoothingMax.setFont(font)
        self.lblPaletteSmoothingMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPaletteSmoothingMax.setObjectName("lblPaletteSmoothingMax")
        self.gridLayout_2.addWidget(self.lblPaletteSmoothingMax, 1, 3, 1, 1)
        self.sliderPaletteSmoothing = QtWidgets.QSlider(self.widget)
        self.sliderPaletteSmoothing.setStyleSheet("")
        self.sliderPaletteSmoothing.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPaletteSmoothing.setObjectName("sliderPaletteSmoothing")
        self.gridLayout_2.addWidget(self.sliderPaletteSmoothing, 1, 1, 1, 2)
        self.lePaletteSmoothingValue = QtWidgets.QLineEdit(self.widget)
        self.lePaletteSmoothingValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lePaletteSmoothingValue.setObjectName("lePaletteSmoothingValue")
        self.gridLayout_2.addWidget(self.lePaletteSmoothingValue, 0, 2, 1, 1)
        self.gbGenerateAlgorithm = QtWidgets.QGroupBox(self.gbGenerateParams)
        self.gbGenerateAlgorithm.setGeometry(QtCore.QRect(241, 30, 226, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbGenerateAlgorithm.setFont(font)
        self.gbGenerateAlgorithm.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGenerateAlgorithm.setObjectName("gbGenerateAlgorithm")
        self.rbVoronoyDiagram = QtWidgets.QRadioButton(self.gbGenerateAlgorithm)
        self.rbVoronoyDiagram.setGeometry(QtCore.QRect(10, 40, 209, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbVoronoyDiagram.setFont(font)
        self.rbVoronoyDiagram.setChecked(True)
        self.rbVoronoyDiagram.setObjectName("rbVoronoyDiagram")
        self.rbPerlinNoise = QtWidgets.QRadioButton(self.gbGenerateAlgorithm)
        self.rbPerlinNoise.setGeometry(QtCore.QRect(10, 80, 209, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbPerlinNoise.setFont(font)
        self.rbPerlinNoise.setObjectName("rbPerlinNoise")
        self.rbRangeInCrack = QtWidgets.QRadioButton(self.gbGenerateAlgorithm)
        self.rbRangeInCrack.setGeometry(QtCore.QRect(10, 120, 209, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbRangeInCrack.setFont(font)
        self.rbRangeInCrack.setObjectName("rbRangeInCrack")
        self.gbGenerationSide = QtWidgets.QGroupBox(self.tabProperties)
        self.gbGenerationSide.setGeometry(QtCore.QRect(215, 370, 266, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbGenerationSide.setFont(font)
        self.gbGenerationSide.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGenerationSide.setObjectName("gbGenerationSide")
        self.cbRight = QtWidgets.QCheckBox(self.gbGenerationSide)
        self.cbRight.setGeometry(QtCore.QRect(10, 25, 59, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbRight.setFont(font)
        self.cbRight.setChecked(True)
        self.cbRight.setObjectName("cbRight")
        self.cbMiddle = QtWidgets.QCheckBox(self.gbGenerationSide)
        self.cbMiddle.setGeometry(QtCore.QRect(85, 25, 82, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbMiddle.setFont(font)
        self.cbMiddle.setChecked(True)
        self.cbMiddle.setObjectName("cbMiddle")
        self.cbLeft = QtWidgets.QCheckBox(self.gbGenerationSide)
        self.cbLeft.setGeometry(QtCore.QRect(185, 25, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbLeft.setFont(font)
        self.cbLeft.setChecked(True)
        self.cbLeft.setObjectName("cbLeft")
        self.gbCeramicColor = QtWidgets.QGroupBox(self.tabProperties)
        self.gbCeramicColor.setGeometry(QtCore.QRect(355, 5, 336, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbCeramicColor.setFont(font)
        self.gbCeramicColor.setAlignment(QtCore.Qt.AlignCenter)
        self.gbCeramicColor.setFlat(False)
        self.gbCeramicColor.setCheckable(False)
        self.gbCeramicColor.setObjectName("gbCeramicColor")
        self.rbBrown = QtWidgets.QRadioButton(self.gbCeramicColor)
        self.rbBrown.setGeometry(QtCore.QRect(10, 40, 308, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbBrown.setFont(font)
        self.rbBrown.setObjectName("rbBrown")
        self.rbBrown.setChecked(True)
        self.rbWhite = QtWidgets.QRadioButton(self.gbCeramicColor)
        self.rbWhite.setGeometry(QtCore.QRect(10, 80, 311, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbWhite.setFont(font)
        self.rbWhite.setObjectName("rbWhite")
        self.gbGaussianBlur = QtWidgets.QGroupBox(self.tabProperties)
        self.gbGaussianBlur.setGeometry(QtCore.QRect(490, 446, 201, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGaussianBlur.sizePolicy().hasHeightForWidth())
        self.gbGaussianBlur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbGaussianBlur.setFont(font)
        self.gbGaussianBlur.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGaussianBlur.setObjectName("gbGaussianBlur")
        self.widget_4 = QtWidgets.QWidget(self.gbGaussianBlur)
        self.widget_4.setGeometry(QtCore.QRect(5, 30, 191, 101))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sliderGaussianBlur = QtWidgets.QSlider(self.widget_4)
        self.sliderGaussianBlur.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGaussianBlur.setObjectName("sliderGaussianBlur")
        self.gridLayout_5.addWidget(self.sliderGaussianBlur, 1, 1, 1, 2)
        self.lblGaussianBlurMax = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblGaussianBlurMax.setFont(font)
        self.lblGaussianBlurMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGaussianBlurMax.setObjectName("lblGaussianBlurMax")
        self.gridLayout_5.addWidget(self.lblGaussianBlurMax, 1, 3, 1, 1)
        self.lblGaussianBlurMin = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblGaussianBlurMin.setFont(font)
        self.lblGaussianBlurMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGaussianBlurMin.setObjectName("lblGaussianBlurMin")
        self.gridLayout_5.addWidget(self.lblGaussianBlurMin, 1, 0, 1, 1)
        self.lblGaussianBlurTextValue = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblGaussianBlurTextValue.setFont(font)
        self.lblGaussianBlurTextValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGaussianBlurTextValue.setObjectName("lblGaussianBlurTextValue")
        self.gridLayout_5.addWidget(self.lblGaussianBlurTextValue, 0, 0, 1, 2)
        self.leGaussianBlurValue = QtWidgets.QLineEdit(self.widget_4)
        self.leGaussianBlurValue.setAlignment(QtCore.Qt.AlignCenter)
        self.leGaussianBlurValue.setObjectName("leGaussianBlurValue")
        self.gridLayout_5.addWidget(self.leGaussianBlurValue, 0, 2, 1, 1)
        self.gbIsolatorType = QtWidgets.QGroupBox(self.tabProperties)
        self.gbIsolatorType.setGeometry(QtCore.QRect(5, 5, 336, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbIsolatorType.setFont(font)
        self.gbIsolatorType.setAlignment(QtCore.Qt.AlignCenter)
        self.gbIsolatorType.setObjectName("gbIsolatorType")
        self.rbGlass = QtWidgets.QRadioButton(self.gbIsolatorType)
        self.rbGlass.setGeometry(QtCore.QRect(10, 40, 319, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbGlass.setFont(font)
        self.rbGlass.setChecked(True)
        self.rbGlass.setObjectName("rbGlass")
        self.rbCeramic = QtWidgets.QRadioButton(self.gbIsolatorType)
        self.rbCeramic.setGeometry(QtCore.QRect(10, 80, 319, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rbCeramic.setFont(font)
        self.rbCeramic.setObjectName("rbCeramic")
        self.gbCrackScale = QtWidgets.QGroupBox(self.tabProperties)
        self.gbCrackScale.setGeometry(QtCore.QRect(5, 446, 201, 140))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gbCrackScale.setFont(font)
        self.gbCrackScale.setAlignment(QtCore.Qt.AlignCenter)
        self.gbCrackScale.setObjectName("gbCrackScale")
        self.widget_2 = QtWidgets.QWidget(self.gbCrackScale)
        self.widget_2.setGeometry(QtCore.QRect(5, 30, 191, 101))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblCrackScaleMax = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblCrackScaleMax.setFont(font)
        self.lblCrackScaleMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCrackScaleMax.setObjectName("lblCrackScaleMax")
        self.gridLayout_3.addWidget(self.lblCrackScaleMax, 1, 4, 1, 1)
        self.lblCrackScaleTextValue = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblCrackScaleTextValue.setFont(font)
        self.lblCrackScaleTextValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCrackScaleTextValue.setObjectName("lblCrackScaleTextValue")
        self.gridLayout_3.addWidget(self.lblCrackScaleTextValue, 0, 0, 1, 2)
        self.sliderCrackScale = QtWidgets.QSlider(self.widget_2)
        self.sliderCrackScale.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCrackScale.setObjectName("sliderCrackScale")
        self.gridLayout_3.addWidget(self.sliderCrackScale, 1, 1, 1, 3)
        self.lblCrackScaleMin = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblCrackScaleMin.setFont(font)
        self.lblCrackScaleMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCrackScaleMin.setObjectName("lblCrackScaleMin")
        self.gridLayout_3.addWidget(self.lblCrackScaleMin, 1, 0, 1, 1)
        self.leCrackScaleValue = QtWidgets.QLineEdit(self.widget_2)
        self.leCrackScaleValue.setAlignment(QtCore.Qt.AlignCenter)
        self.leCrackScaleValue.setObjectName("leCrackScaleValue")
        self.gridLayout_3.addWidget(self.leCrackScaleValue, 0, 3, 1, 1)
        self.mainTabWidget.addTab(self.tabProperties, "")
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Isolator cracker"))
        self.label_2.setText(_translate("MainWindow", "How much isolators compute?"))
        self.lblComputeIsolatorsMin.setText(_translate("MainWindow", "1"))
        self.lblComputeIsolatorsMax.setText(_translate("MainWindow", "12345"))
        self.btnCompute.setText(_translate("MainWindow", "Compute"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.lblFoundIsolators.setText(_translate("MainWindow", "Found <N> <Glass> isolators"))
        self.label_5.setText(_translate("MainWindow", "Choose directory for generated isolators:"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabCompute), _translate("MainWindow", "Compute"))
        self.gbWhiteLimit.setTitle(_translate("MainWindow", "White limit:"))
        self.lblWhiteLimitMin.setText(_translate("MainWindow", "0"))
        self.lblWhiteLimitTextValue.setText(_translate("MainWindow", "value:"))
        self.lblWhiteLimitMax.setText(_translate("MainWindow", "0"))
        self.leWhiteLimitValue.setText(_translate("MainWindow", "0"))
        self.gbGenerateMethod.setTitle(_translate("MainWindow", "Generation method:"))
        self.rbCrackAddition.setText(_translate("MainWindow", "Crack addition"))
        self.rbCrackGeneration.setText(_translate("MainWindow", "Crack generation"))
        self.gbGenerateParams.setTitle(_translate("MainWindow", "Generation parameters:"))
        self.gbPaletteSmoothing.setTitle(_translate("MainWindow", "Palette smoothing:"))
        self.lblPaletteSmoothingMin.setText(_translate("MainWindow", "0"))
        self.lblPaletteSmoothingTextValue.setText(_translate("MainWindow", "value:"))
        self.lblPaletteSmoothingMax.setText(_translate("MainWindow", "0"))
        self.lePaletteSmoothingValue.setText(_translate("MainWindow", "0"))
        self.gbGenerateAlgorithm.setTitle(_translate("MainWindow", "Coloring algorithm:"))
        self.rbVoronoyDiagram.setText(_translate("MainWindow", "Voronoy diagram"))
        self.rbPerlinNoise.setText(_translate("MainWindow", "Perlin noise"))
        self.rbRangeInCrack.setText(_translate("MainWindow", "Range in crack"))
        self.gbGenerationSide.setTitle(_translate("MainWindow", "Generation sides:"))
        self.cbRight.setText(_translate("MainWindow", "Left"))
        self.cbMiddle.setText(_translate("MainWindow", "Middle"))
        self.cbLeft.setText(_translate("MainWindow", "Right"))
        self.gbCeramicColor.setTitle(_translate("MainWindow", "Ceramic color:"))
        self.rbBrown.setText(_translate("MainWindow", "Brown"))
        self.rbWhite.setText(_translate("MainWindow", "White"))
        self.gbGaussianBlur.setTitle(_translate("MainWindow", "Gaussian blur:"))
        self.lblGaussianBlurMax.setText(_translate("MainWindow", "0"))
        self.lblGaussianBlurMin.setText(_translate("MainWindow", "0"))
        self.lblGaussianBlurTextValue.setText(_translate("MainWindow", "value:"))
        self.leGaussianBlurValue.setText(_translate("MainWindow", "0"))
        self.gbIsolatorType.setTitle(_translate("MainWindow", "Isolator type:"))
        self.rbGlass.setText(_translate("MainWindow", "Glass"))
        self.rbCeramic.setText(_translate("MainWindow", "Ceramic"))
        self.gbCrackScale.setTitle(_translate("MainWindow", "Crack scale:"))
        self.lblCrackScaleMax.setText(_translate("MainWindow", "0"))
        self.lblCrackScaleTextValue.setText(_translate("MainWindow", "value:"))
        self.lblCrackScaleMin.setText(_translate("MainWindow", "0"))
        self.leCrackScaleValue.setText(_translate("MainWindow", "0"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabProperties), _translate("MainWindow", "Properties"))
import design.files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
